const API_BASE_URL = "http://localhost:3001/api/v1";
// const API_BASE_URL = "https://api-gi52ugpsnq-uc.a.run.app/api/v1";

export const api = {
  baseURL: API_BASE_URL,

  // Endpoints
  endpoints: {
    auth: {
      login: "/auth/login",
      google: "/auth/google",
      register: "/auth/register",
      logout: "/auth/logout",
      me: "/auth/me",
      forgotPassword: "/auth/forgot-password",
      resetPassword: "/auth/reset-password",
    },
    tours: {
      getAll: "/tours",
      getById: (id: string) => `/tours/${id}`,
      getByCountry: (countryId: string) => `/tours/country/${countryId}`,
      getFeatured: "/tours/featured",
      getPopular: "/tours/popular",
      search: "/tours/search",
      getMyAssigned: "/tours/my-assigned-tours",
      create: "/tours",
      update: "/tours/:id",
      delete: "/tours/:id",
    },
    tourExecution: {
      getByTour: (tourId: string, departureDate?: string) =>
        `/tour-execution/${tourId}${departureDate ? `?departureDate=${encodeURIComponent(departureDate)}` : ""}`,
      updateAttendance: (tourId: string) => `/tour-execution/${tourId}/attendance`,
      updateActivity: (tourId: string) => `/tour-execution/${tourId}/activity`,
    },
    countries: {
      getAll: "/countries",
      getById: (id: string) => `/countries/${id}`,
      getPopular: "/countries/popular",
      getByContinent: (continent: string) =>
        `/countries/continent/${continent}`,
      create: "/countries",
      update: "/countries/:id",
      delete: "/countries/:id",
    },
    bookings: {
      getAll: "/bookings",
      create: "/bookings",
      getById: (id: string) => `/bookings/${id}`,
      update: (id: string) => `/bookings/${id}`,
      cancel: (id: string) => `/bookings/${id}/cancel`,
      cancellationPreview: (id: string) =>
        `/bookings/${id}/cancellation-preview`,
      getByTour: (tourId: string) => `/bookings?tour=${tourId}`,
      submitDocuments: (id: string) => `/bookings/${id}/submit-documents`,
      toggleDocVerification: (id: string) =>
        `/bookings/${id}/toggle-doc-verification`,
    },
    lifetimeDeposits: {
      getMyDeposits: "/lifetime-deposits/my-deposits",
      validate: "/lifetime-deposits/validate",
    },
    reviews: {
      getAll: "/reviews",
      create: "/reviews",
      getById: (id: string) => `/reviews/${id}`,
      update: (id: string) => `/reviews/${id}`,
      delete: "/reviews/:id",
    },
    users: {
      updateMe: "/users/update-me",
      getMyBookings: "/users/my-bookings",
      getMyReviews: "/users/my-reviews",
      getWishlist: "/users/wishlist",
      toggleWishlist: (tourId: string) => `/users/wishlist/${tourId}`,
      getAllAdmin: "/users",
      getStats: "/users/stats",
      getById: (id: string) => `/users/${id}`,
      updateById: (id: string) => `/users/${id}`,
      deactivateById: (id: string) => `/users/${id}`,
    },
    holdSpaces: {
      create: "/hold-spaces",
      getMyHolds: "/hold-spaces/my-holds",
      getById: (id: string) => `/hold-spaces/${id}`,
      release: (id: string) => `/hold-spaces/${id}/release`,
    },
    blogs: {
      getAll: "/blogs",
      getBySlug: (slug: string) => `/blogs/${slug}`,
      getFeatured: "/blogs/featured",
      getCategories: "/blogs/categories",
      getByCategory: (category: string) => `/blogs/category/${category}`,
      search: "/blogs/search",
      getMyBlogs: "/blogs/me/blogs",
      getMyBlog: (id: string) => `/blogs/me/blogs/${id}`,
      create: "/blogs",
      update: (id: string) => `/blogs/${id}`,
      delete: (id: string) => `/blogs/${id}`,
    },
    travelStyles: {
      getAll: "/travel-styles",
      getById: (id: string) => `/travel-styles/${id}`,
      getBySlug: (slug: string) => `/travel-styles/slug/${slug}`,
      create: "/travel-styles",
      update: (id: string) => `/travel-styles/${id}`,
      delete: (id: string) => `/travel-styles/${id}`,
    },
    interests: {
      getAll: "/interests",
      getById: (id: string) => `/interests/${id}`,
      getBySlug: (slug: string) => `/interests/slug/${slug}`,
      create: "/interests",
      update: (id: string) => `/interests/${id}`,
      delete: (id: string) => `/interests/${id}`,
    },
    continents: {
      getAll: "/continents",
      getById: (id: string) => `/continents/${id}`,
      create: "/continents",
      update: (id: string) => `/continents/${id}`,
      delete: (id: string) => `/continents/${id}`,
    },
    queries: {
      getAll: "/queries",
      create: "/queries",
      update: (id: string) => `/queries/${id}`,
      delete: (id: string) => `/queries/${id}`,
    },
    promoCodes: {
      getAll: "/promo-codes",
      getById: (id: string) => `/promo-codes/${id}`,
      create: "/promo-codes",
      update: (id: string) => `/promo-codes/${id}`,
      delete: (id: string) => `/promo-codes/${id}`,
      apply: "/promo-codes/apply",
      checkStatus: (tourId: string) => `/promo-codes/check/${tourId}`,
    },
    activities: {
      getAll: "/activities",
      getById: (id: string) => `/activities/${id}`,
      create: "/activities",
      update: (id: string) => `/activities/${id}`,
      delete: (id: string) => `/activities/${id}`,
    },
    hotels: {
      getAll: "/hotels",
      getById: (id: string) => `/hotels/${id}`,
      create: "/hotels",
      update: (id: string) => `/hotels/${id}`,
      delete: (id: string) => `/hotels/${id}`,
    },
    installments: {
      createPlan: "/installments/create-plan",
      activate: "/installments/activate",
      sync: (bookingId: string) => `/installments/${bookingId}/sync`,
      preview: "/installments/preview",
    },
    physicalRatings: {
      getAll: "/physical-ratings",
      getById: (id: string) => `/physical-ratings/${id}`,
    },
    discounts: {
      getAll: "/discounts",
      getActive: "/discounts/active",
      getById: (id: string) => `/discounts/${id}`,
    },
    affiliates: {
      apply: "/affiliates/apply",
      me: "/affiliates/me",
      myReferrals: "/affiliates/me/referrals",
      myPayouts: "/affiliates/me/payouts",
      track: (code: string) => `/affiliates/track/${code}`,
      getAll: "/affiliates",
      stats: "/affiliates/stats",
      getById: (id: string) => `/affiliates/${id}`,
      approve: (id: string) => `/affiliates/${id}/approve`,
      reject: (id: string) => `/affiliates/${id}/reject`,
      suspend: (id: string) => `/affiliates/${id}/suspend`,
      updateCommission: (id: string) => `/affiliates/${id}/commission`,
      payout: (id: string) => `/affiliates/${id}/payout`,
    },
  },
};
